### PR TITLE
+ karplus_rings.lua

### PR DESCRIPTION
**Pull request by pq**
/cc @tehn @GoneCaving

### CODE REVIEW

**Comment by tehn** [comment]
which script(s) use this?

i'm mostly in favor of engines living with their primary script, with the primary author... so that someday this `we` repository will just be tests... or perhaps go away entirely.

(this is anticipating the supercollider update where .scd files can be run, so we won't have multiple-engine collision problems... where each script should include the file of their engine in the same repo)

if this engine is truly orphaned we can merge this, certainly

**Comment by pq** [comment]
> which script(s) use this?

i'm working on a multi-engine earthsea that uses this (and polysub).

>  i'm mostly in favor of engines living with their primary script, with the primary author...

ah.  that's interesting.

> if this engine is truly orphaned

i'm really not sure tbh.

i know @GoneCaving contributed a bit and **burn** on lines provided the initial implementation.

i'm happy to give it a home if they don't want it but i'm not sure my earthsea variations would the best "primary script"...  i'll think on it.

**Comment by tehn** [comment]
in the meantime i'm happy to have it here (given it isn't already hosted somewhere else and will create a conflict)

otherwise your ES mod will need to proclaim it "requires" whatever other project does in fact have it installed. dupe engines is a pitfall right now

**Comment by pq** [comment]
having it here sounds good to me.

feel free to review and merge?

thanks!

**Pull request merged**
